version: '3.8'

services:
  # Servicio de Jenkins para integraci칩n continua
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - servidores-net

  # Servicio de SonarQube para an치lisis de c칩digo est치tico
  sonarqube:
    image: sonarqube:lts-community
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    depends_on:
      - db
    networks:
      - servidores-net

  # Base de datos para SonarQube
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - servidores-net

  # Servicio de Cypress para pruebas End-to-End
  cypress:
    image: cypress/included:13.13.1
    container_name: cypress
    volumes:
      - ./cypress:/e2e
    working_dir: /e2e
    entrypoint: tail -f /dev/null
    networks:
      - servidores-net

  # === Servicios para Backstage ===
  backstage-backend:
    build:
      context: ./yavu
      dockerfile: Dockerfile
    container_name: backstage_backend
    environment:
      - NODE_ENV=development
      - POSTGRES_HOST=backstage_db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=backstage
      - POSTGRES_PASSWORD=backstage
      - POSTGRES_DATABASE=backstage
      - AUTH_GITHUB_CLIENT_ID=${AUTH_GITHUB_CLIENT_ID}
      - AUTH_GITHUB_CLIENT_SECRET=${AUTH_GITHUB_CLIENT_SECRET}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    ports:
      - "7007:7007"
    depends_on:
      - backstage_db
    networks:
      - servidores-net

  backstage-frontend:
    image: nginx:1.25.3-alpine
    container_name: backstage_frontend
    ports:
      - "7008:80"
    volumes:
      - ./yavu/packages/app/dist:/usr/share/nginx/html:ro
    networks:
      - servidores-net

  backstage_db:
    image: postgres:13
    container_name: backstage_db
    environment:
      - POSTGRES_USER=backstage
      - POSTGRES_PASSWORD=backstage
      - POSTGRES_DB=backstage
    volumes:
      - backstage_postgres_data:/var/lib/postgresql/data
    networks:
      - servidores-net

volumes:
  jenkins_home:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgres_data:
  backstage_postgres_data: {}

networks:
  servidores-net:
    driver: bridge
