# docker-compose.yml

version: '3.8'

services:
  # Servicio de Jenkins para integración continua
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins
    ports:
      - "8081:8080" # Puerto para acceder a la interfaz de Jenkins
      - "50000:50000" # Puerto para los agentes de Jenkins
    volumes:
      - jenkins_home:/var/jenkins_home # Volumen para persistir la configuración de Jenkins
    networks:
      - servidores-net

  # Servicio de SonarQube para análisis de código estático
  sonarqube:
    image: sonarqube:lts-community
    container_name: sonarqube
    ports:
      - "9000:9000" # Puerto para acceder a la interfaz de SonarQube
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    depends_on:
      - db # SonarQube no arrancará hasta que la base de datos esté lista
    networks:
      - servidores-net

  # Base de datos PostgreSQL para SonarQube
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    volumes:
      - postgres_data:/var/lib/postgresql/data # Volumen para persistir los datos de la BD
    networks:
      - servidores-net

  # Servicio de Cypress para pruebas End-to-End
  # Este contenedor no ejecuta nada por defecto, se usa para lanzar comandos.
  cypress:
    image: cypress/included:13.13.1
    container_name: cypress
    volumes:
      - ./cypress:/e2e # Mapea una carpeta local 'cypress' al contenedor
    working_dir: /e2e
    # Mantenemos el contenedor vivo para poder ejecutar comandos en él
    entrypoint: tail -f /dev/null
    networks:
      - servidores-net

# Definición de los volúmenes para persistir datos
volumes:
  jenkins_home:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgres_data:

# Definición de la red para que los contenedores se comuniquen
networks:
  servidores-net:
    driver: bridge
