# app-config.production.yaml
...
backend:
  baseUrl: http://localhost:7007
  listen:
    port: 7007
  auth:
    keys:
      # This is the secret key that will be shared between the frontend and the backend.
      # It can be any string you want, but must be the same in both files.
      - secret: my-development-secret-key-12345
  
  # Database configuration should point to the correct database service
  database:
    client: pg
    connection:
      host: backstage_db
      port: 5432
      user: backstage
      password: backstage
      database: backstage
      
auth:
  providers:
    guest: {}

catalog:
  locations:
    # Local example data, replace this with your production config
    - type: file
      target: ./examples/entities.yaml
      rules:
        - allow: [Component, API, Template, Location, System, Group, User, Domain]

    # Local example template
    - type: file
      target: ./examples/template/template.yaml
      rules:
        - allow: [Template]

    # Local example organizational data
    - type: file
      target: ./examples/org.yaml
      rules:
        - allow: [User, Group]
...
