app:
  baseUrl: http://localhost:7008

backend:
  cors:
    origin: http://localhost:7008
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST} # Lee la variable de compose
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      database: ${POSTGRES_DATABASE}

auth:
  providers:
    github:
      production:
        clientId: ${AUTH_GITHUB_CLIENT_ID} # Lee la variable de compose
        clientSecret: ${AUTH_GITHUB_CLIENT_SECRET} # Lee la variable de compose

techdocs:
  builder: 'local'
  generator:
    runIn: 'docker'
  publisher:
    type: 'local'
