app:
  title: Yavu Backstage
  baseUrl: http://localhost:7008

organization:
  name: My Company

backend:
  baseUrl: http://localhost:7007
  listen:
    port: 7007
  csp:
    connect-src: ["'self'", 'http:', 'https:']
  cors:
    # Permite que el frontend en el puerto 7008 se comunique con el backend
    origin: http://localhost:7008
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  database:
    # Esta es la configuración base. Los valores (${...}) serán reemplazados
    # por app-config.local.yaml o las variables de entorno de Docker.
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      database: ${POSTGRES_DATABASE}

integrations:
  github:
    - host: github.com
      # El token se provee desde un archivo local o variable de entorno para seguridad
      token: ${GITHUB_TOKEN}

# Esta sección es CRÍTICA para que el frontend (en :7008) pueda
# encontrar y hablar con el backend (en :7007).
proxy:
  '/api':
    target: http://localhost:7007
    changeOrigin: true

auth:
  providers:
    # La configuración de GitHub usa placeholders. Los valores reales
    # se proporcionan desde app-config.local.yaml o docker-compose.yml.
    github:
      development:
        clientId: ${AUTH_GITHUB_CLIENT_ID}
        clientSecret: ${AUTH_GITHUB_CLIENT_SECRET}
    guest: {}

techdocs:
  builder: 'local'
  generator:
    runIn: 'docker'
  publisher:
    type: 'local'

scaffolder:
  # Configuración por defecto

catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, System, API, Resource, Location]
  locations:
    # Carga los usuarios y grupos para el login (el archivo que creaste)
    - type: file
      target: ../../examples/org.yaml
      rules:
        - allow: [User, Group]
    
    # Datos de ejemplo de Backstage
    - type: file
      target: ../../examples/entities.yaml

    - type: file
      target: ../../examples/template/template.yaml
      rules:
        - allow: [Template]
